### PR TITLE
feat: make options optional and add declaration file

### PR DESCRIPTION
**Pull request by zanminkian**

### CODE REVIEW

**Comment by legend80s** [comment]
lint failed 😅
image

**Comment by legend80s** [comment]
I will fix it and add pre-commit to lint 😄.

**Comment by legend80s** [comment]
+ git-commit-msg-linter@4.7.1

**Comment by zanminkian** [comment]
image

**Comment by legend80s** [comment]
Added in git-commit-msg-linter@4.7.2

**Pull request merged**
