### PR TITLE
refactor: make hooks dir cleaner

### PR DESCRIPTION
**Pull request by zanminkian**
From
image
to
image

### CODE REVIEW

**Comment by legend80s** [comment]
It was clean as you expected when the package was born but we came across the problem below 😅 

> Solve the problem of [Wishlist: support for ES6 modules. #14].
> https://github.com/legend80s/commit-msg-linter/issues/14

**Comment by zanminkian** [comment]
@legend80s Adding `#!/usr/bin/env -S sh -c "cat commit-msg | node --input-type=commonjs"` on the top of `commit-msg` can support `"type": "module"` project. Please review it again.

**Comment by legend80s** [comment]
It is great! Published + git-commit-msg-linter@4.8.0!

**Comment by legend80s** [comment]
@zanminkian Please look into this issue https://github.com/legend80s/git-commit-msg-linter/issues/35.

**Pull request merged**
